model: ScaleShiftMACE
num_channels: 32
max_L: 0
r_max: 4.0
name: model_rnd_e_scmace_lr0.0001_80_10
model_dir: model_Fe_Si_B_260311/scmace_0.0001_80_10_rnd_e
log_dir: model_Fe_Si_B_260311/scmace_0.0001_80_10_rnd_e/log
checkpoints_dir: model_Fe_Si_B_260311/scmace_0.0001_80_10_rnd_e/checkpoints
results_dir: model_Fe_Si_B_260311/scmace_0.0001_80_10_rnd_e/results
train_file: model_Fe_Si_B_260311/train_rnd_e.xyz
valid_fraction: 0.1
test_file: model_Fe_Si_B_260311/test_rnd_e.xyz
energy_key: REF_energy
forces_key: REF_forces
batch_size: 10
max_num_epochs: 80
optimizer: adam
lr: 0.0001
device: cpu
seed: 123
swa: true
