model: ScaleShiftMACE
num_channels: 32
max_L: 0
r_max: 4.0
name: model_test_scmace_lr0.0001_40_10
model_dir: model_Fe_Si_B_260311/scmace_0.0001_40_10_test
log_dir: model_Fe_Si_B_260311/scmace_0.0001_40_10_test/log
checkpoints_dir: model_Fe_Si_B_260311/scmace_0.0001_40_10_test/checkpoints
results_dir: model_Fe_Si_B_260311/scmace_0.0001_40_10_test/results
train_file: model_Fe_Si_B_260311/train_test.xyz
valid_fraction: 0.1
test_file: model_Fe_Si_B_260311/test_test.xyz
energy_key: REF_energy
forces_key: REF_forces
batch_size: 10
max_num_epochs: 40
optimizer: adam
lr: 0.0001
device: cpu
seed: 123
