foundation_model: MACE-matpes-pbe-omat-ft.model
multiheads_finetuning: false
freeze: 6
name: model_rnd_e_matpes_nofe8b4_freeze_6_lr0.0001_1000_10_567
model_dir: model_Fe_Si_B_260311/freeze_training/matpes_nofe8b4_freeze_6_0.0001_1000_10_rnd_e_567
log_dir: model_Fe_Si_B_260311/freeze_training/matpes_nofe8b4_freeze_6_0.0001_1000_10_rnd_e_567/log
checkpoints_dir: model_Fe_Si_B_260311/freeze_training/matpes_nofe8b4_freeze_6_0.0001_1000_10_rnd_e_567/checkpoints
results_dir: model_Fe_Si_B_260311/freeze_training/matpes_nofe8b4_freeze_6_0.0001_1000_10_rnd_e_567/results
train_file: model_Fe_Si_B_260311/train_rnd_e_no_Fe8B4.xyz
valid_fraction: 0.1
test_file: model_Fe_Si_B_260311/test_rnd_e_no_Fe8B4.xyz
energy_key: REF_energy
forces_key: REF_forces
batch_size: 10
max_num_epochs: 1000
lr: 0.0001
device: cuda
seed: 567
restart_latest: true
