foundation_model: MACE-matpes-pbe-omat-ft.model
multiheads_finetuning: false
name: model_test_matpes_lr0.0001_40_10
model_dir: model_Fe_Si_B_260311/fine_tuning/matpes_0.0001_40_10_test
log_dir: model_Fe_Si_B_260311/fine_tuning/matpes_0.0001_40_10_test/log
checkpoints_dir: model_Fe_Si_B_260311/fine_tuning/matpes_0.0001_40_10_test/checkpoints
results_dir: model_Fe_Si_B_260311/fine_tuning/matpes_0.0001_40_10_test/results
train_file: model_Fe_Si_B_260311/train_test.xyz
valid_fraction: 0.1
test_file: model_Fe_Si_B_260311/test_test.xyz
energy_key: REF_energy
forces_key: REF_forces
batch_size: 10
max_num_epochs: 40
lr: 0.0001
device: cpu
seed: 123
