foundation_model: MACE-matpes-pbe-omat-ft.model
multiheads_finetuning: false
name: model_rnd_e_MACE-matpes-pbe-omat-ft_lr0.0001_40epochs_10batch
model_dir: model_Fe_Si_B_260311/fine_tunning
log_dir: model_Fe_Si_B_260311/fine_tunning/log
checkpoints_dir: model_Fe_Si_B_260311/fine_tunning/checkpoints
results_dir: model_Fe_Si_B_260311/fine_tunning/results
train_file: model_Fe_Si_B_260311/train_rnd_e.xyz
valid_fraction: 0.1
test_file: model_Fe_Si_B_260311/test_rnd_e.xyz
energy_key: REF_energy
forces_key: REF_forces
batch_size: 10
max_num_epochs: 40
lr: 0.0001
device: cpu
seed: 123
